package com.card.mapper;

import com.card.model.Lovefeelingrecord;
import com.card.model.LovefeelingrecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LovefeelingrecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovefeelingrecord
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    int countByExample(LovefeelingrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovefeelingrecord
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    int deleteByExample(LovefeelingrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovefeelingrecord
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    int insert(Lovefeelingrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovefeelingrecord
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    int insertSelective(Lovefeelingrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovefeelingrecord
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    List<Lovefeelingrecord> selectByExample(LovefeelingrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovefeelingrecord
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") Lovefeelingrecord record, @Param("example") LovefeelingrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lovefeelingrecord
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    int updateByExample(@Param("record") Lovefeelingrecord record, @Param("example") LovefeelingrecordExample example);
}