package com.card.model;

import java.util.ArrayList;
import java.util.List;

public class FeellevelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table feellevel
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table feellevel
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table feellevel
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feellevel
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public FeellevelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feellevel
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feellevel
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feellevel
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feellevel
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feellevel
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feellevel
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feellevel
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feellevel
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feellevel
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feellevel
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table feellevel
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFeelLevelIsNull() {
            addCriterion("feel_level is null");
            return (Criteria) this;
        }

        public Criteria andFeelLevelIsNotNull() {
            addCriterion("feel_level is not null");
            return (Criteria) this;
        }

        public Criteria andFeelLevelEqualTo(Integer value) {
            addCriterion("feel_level =", value, "feelLevel");
            return (Criteria) this;
        }

        public Criteria andFeelLevelNotEqualTo(Integer value) {
            addCriterion("feel_level <>", value, "feelLevel");
            return (Criteria) this;
        }

        public Criteria andFeelLevelGreaterThan(Integer value) {
            addCriterion("feel_level >", value, "feelLevel");
            return (Criteria) this;
        }

        public Criteria andFeelLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("feel_level >=", value, "feelLevel");
            return (Criteria) this;
        }

        public Criteria andFeelLevelLessThan(Integer value) {
            addCriterion("feel_level <", value, "feelLevel");
            return (Criteria) this;
        }

        public Criteria andFeelLevelLessThanOrEqualTo(Integer value) {
            addCriterion("feel_level <=", value, "feelLevel");
            return (Criteria) this;
        }

        public Criteria andFeelLevelIn(List<Integer> values) {
            addCriterion("feel_level in", values, "feelLevel");
            return (Criteria) this;
        }

        public Criteria andFeelLevelNotIn(List<Integer> values) {
            addCriterion("feel_level not in", values, "feelLevel");
            return (Criteria) this;
        }

        public Criteria andFeelLevelBetween(Integer value1, Integer value2) {
            addCriterion("feel_level between", value1, value2, "feelLevel");
            return (Criteria) this;
        }

        public Criteria andFeelLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("feel_level not between", value1, value2, "feelLevel");
            return (Criteria) this;
        }

        public Criteria andFeelIsNull() {
            addCriterion("feel is null");
            return (Criteria) this;
        }

        public Criteria andFeelIsNotNull() {
            addCriterion("feel is not null");
            return (Criteria) this;
        }

        public Criteria andFeelEqualTo(String value) {
            addCriterion("feel =", value, "feel");
            return (Criteria) this;
        }

        public Criteria andFeelNotEqualTo(String value) {
            addCriterion("feel <>", value, "feel");
            return (Criteria) this;
        }

        public Criteria andFeelGreaterThan(String value) {
            addCriterion("feel >", value, "feel");
            return (Criteria) this;
        }

        public Criteria andFeelGreaterThanOrEqualTo(String value) {
            addCriterion("feel >=", value, "feel");
            return (Criteria) this;
        }

        public Criteria andFeelLessThan(String value) {
            addCriterion("feel <", value, "feel");
            return (Criteria) this;
        }

        public Criteria andFeelLessThanOrEqualTo(String value) {
            addCriterion("feel <=", value, "feel");
            return (Criteria) this;
        }

        public Criteria andFeelLike(String value) {
            addCriterion("feel like", value, "feel");
            return (Criteria) this;
        }

        public Criteria andFeelNotLike(String value) {
            addCriterion("feel not like", value, "feel");
            return (Criteria) this;
        }

        public Criteria andFeelIn(List<String> values) {
            addCriterion("feel in", values, "feel");
            return (Criteria) this;
        }

        public Criteria andFeelNotIn(List<String> values) {
            addCriterion("feel not in", values, "feel");
            return (Criteria) this;
        }

        public Criteria andFeelBetween(String value1, String value2) {
            addCriterion("feel between", value1, value2, "feel");
            return (Criteria) this;
        }

        public Criteria andFeelNotBetween(String value1, String value2) {
            addCriterion("feel not between", value1, value2, "feel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table feellevel
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 24 21:18:50 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table feellevel
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}