package com.card.model;

public class Feellevel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feellevel.feel_level
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    private Integer feelLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feellevel.feel
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    private String feel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feellevel.feel_level
     *
     * @return the value of feellevel.feel_level
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public Integer getFeelLevel() {
        return feelLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feellevel.feel_level
     *
     * @param feelLevel the value for feellevel.feel_level
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public void setFeelLevel(Integer feelLevel) {
        this.feelLevel = feelLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feellevel.feel
     *
     * @return the value of feellevel.feel
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public String getFeel() {
        return feel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feellevel.feel
     *
     * @param feel the value for feellevel.feel
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public void setFeel(String feel) {
        this.feel = feel == null ? null : feel.trim();
    }
}