package com.card.model;

import java.util.Date;

public class Lovefeelingrecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovefeelingrecord.user_id
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovefeelingrecord.song_id
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    private Integer songId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lovefeelingrecord.time
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovefeelingrecord.user_id
     *
     * @return the value of lovefeelingrecord.user_id
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovefeelingrecord.user_id
     *
     * @param userId the value for lovefeelingrecord.user_id
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovefeelingrecord.song_id
     *
     * @return the value of lovefeelingrecord.song_id
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public Integer getSongId() {
        return songId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovefeelingrecord.song_id
     *
     * @param songId the value for lovefeelingrecord.song_id
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public void setSongId(Integer songId) {
        this.songId = songId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lovefeelingrecord.time
     *
     * @return the value of lovefeelingrecord.time
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lovefeelingrecord.time
     *
     * @param time the value for lovefeelingrecord.time
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }
}