package com.card.model;

public class Song {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.song_id
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    private Integer songId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.name
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.path
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.image_path
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    private String imagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.uploaduser_id
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    private Integer uploaduserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column song.love_num
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    private Integer loveNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.song_id
     *
     * @return the value of song.song_id
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public Integer getSongId() {
        return songId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.song_id
     *
     * @param songId the value for song.song_id
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public void setSongId(Integer songId) {
        this.songId = songId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.name
     *
     * @return the value of song.name
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.name
     *
     * @param name the value for song.name
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.path
     *
     * @return the value of song.path
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.path
     *
     * @param path the value for song.path
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.image_path
     *
     * @return the value of song.image_path
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.image_path
     *
     * @param imagePath the value for song.image_path
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.uploaduser_id
     *
     * @return the value of song.uploaduser_id
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public Integer getUploaduserId() {
        return uploaduserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.uploaduser_id
     *
     * @param uploaduserId the value for song.uploaduser_id
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public void setUploaduserId(Integer uploaduserId) {
        this.uploaduserId = uploaduserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column song.love_num
     *
     * @return the value of song.love_num
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public Integer getLoveNum() {
        return loveNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column song.love_num
     *
     * @param loveNum the value for song.love_num
     *
     * @mbggenerated Mon Jun 24 21:18:50 CST 2019
     */
    public void setLoveNum(Integer loveNum) {
        this.loveNum = loveNum;
    }
}